// packages/assistant-react/src/TourAssistantPrompt.tsx
import type { FormEvent, JSX } from 'react';
import { useTourAssistantContext } from './TourAssistantContext';
import { Tooltip, TooltipContent, TooltipTrigger } from './Tooltip';

export interface TourAssistantPromptProps {
  placeholder?: string;
}

export function TourAssistantPrompt({
  placeholder = 'Ask the tour…',
}: TourAssistantPromptProps = {}): JSX.Element | null {
  const {
    open,
    query,
    results,
    currentTourId,
    loadingAnimation,
    inputRef,
    setQuery,
    submit,
    close,
    jumpTo,
  } =
    useTourAssistantContext();

  if (!open) return null;

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    submit();
  };

  return (
    <div
      className="tour-assistant"
      role="region"
      aria-label="Tour assistant"
      data-tour="tour-assistant-prompt"
    >
      <form
        className="tour-assistant-form"
        onSubmit={handleSubmit}
        data-tour="tour-assistant-form"
      >
        <span
          className={`tour-assistant-icon tour-assistant-icon--${loadingAnimation}`}
          aria-hidden="true"
        >
          <span className={`tour-loader tour-loader--${loadingAnimation}`} />
        </span>
        <input
          ref={inputRef}
          type="text"
          className="tour-assistant-input"
          placeholder={placeholder}
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          autoComplete="off"
          spellCheck={false}
          aria-label="Ask the tour assistant"
          data-tour="tour-assistant-input"
        />
        <button
          type="submit"
          className="tour-assistant-send"
          disabled={query.trim().length < 2}
          aria-label="Search"
          data-tour="tour-assistant-send"
        >
          →
        </button>
        <button
          type="button"
          className="tour-assistant-close"
          onClick={close}
          aria-label="Hide assistant"
          data-tour="tour-assistant-close"
        >
          ✕
        </button>
      </form>

      {query.trim().length >= 2 && results.length === 0 && (
        <p className="tour-assistant-empty" data-tour="tour-assistant-empty">
          No matching steps. Try different words.
        </p>
      )}

      {results.length > 0 && (
        <ul
          className="tour-assistant-results"
          role="listbox"
          data-tour="tour-assistant-results"
        >
          {results.map((match) => (
            <li key={`${match.kind ?? 'step'}:${match.tourId}:${match.stepId}:${match.chapter ?? ''}`}>
              <Tooltip>
                <TooltipTrigger asChild>
                  <button
                    type="button"
                    className="tour-assistant-result"
                    onClick={() => jumpTo(match)}
                    data-tour="tour-assistant-result"
                  >
                    <span className="tour-assistant-result-title">{match.title}</span>
                    {match.snippet && (
                      <span className="tour-assistant-result-snippet">
                        {stripTourMarkup(match.snippet)}
                      </span>
                    )}
                    <span className="tour-assistant-result-meta">
                      <span className="tour-assistant-result-tour">
                        {match.tourId === currentTourId ? 'This tour' : match.tourId}
                        {match.kind === 'chapter' && match.stepCount
                          ? ` • ${match.stepCount} steps`
                          : ''}
                      </span>
                      <span className="tour-assistant-result-jump">
                        {match.kind === 'chapter' ? 'Open flow →' : 'Jump →'}
                      </span>
                    </span>
                  </button>
                </TooltipTrigger>
                <TooltipContent side="top" align="start">
                  {resultTooltip(match.title, match.snippet)}
                </TooltipContent>
              </Tooltip>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}

function stripTourMarkup(snippet: string): string {
  return snippet.replace(/==\|?~?([^=|~]+)~?\|?==/g, '$1');
}

function resultTooltip(title: string, snippet: string | undefined): string {
  const cleanSnippet = snippet ? stripTourMarkup(snippet).trim() : '';
  return cleanSnippet ? `${title}\n\n${cleanSnippet}` : title;
}

export default TourAssistantPrompt;

// packages/assistant-angular/src/lib/tour-assistant-prompt.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  ElementRef,
  Input,
  ViewChild,
  effect,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import type { AssistantMatch } from '@routepilot/assistant';
import { TourAssistantService } from './tour-assistant.service';
import { RpTooltipDirective } from './rp-tooltip.directive';

@Component({
  selector: 'rp-tour-assistant-prompt',
  standalone: true,
  imports: [CommonModule, FormsModule, RpTooltipDirective],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div
      *ngIf="assistant.open()"
      class="tour-assistant"
      role="region"
      aria-label="Tour assistant"
      data-tour="tour-assistant-prompt"
    >
      <form
        class="tour-assistant-form"
        (submit)="handleSubmit($event)"
        data-tour="tour-assistant-form"
      >
        <span
          class="tour-assistant-icon tour-assistant-icon--{{ assistant.loadingAnimation() }}"
          aria-hidden="true"
        >
          <span class="tour-loader tour-loader--{{ assistant.loadingAnimation() }}"></span>
        </span>
        <input
          #inputEl
          type="text"
          class="tour-assistant-input"
          [placeholder]="placeholder"
          [ngModel]="assistant.query()"
          (ngModelChange)="assistant.setQuery($event)"
          name="tour-assistant-query"
          autocomplete="off"
          spellcheck="false"
          aria-label="Ask the tour assistant"
          data-tour="tour-assistant-input"
        />
        <button
          type="submit"
          class="tour-assistant-send"
          [disabled]="assistant.query().trim().length < 2"
          aria-label="Search"
          data-tour="tour-assistant-send"
        >
          &rarr;
        </button>
        <button
          type="button"
          class="tour-assistant-close"
          (click)="assistant.close()"
          aria-label="Hide assistant"
          data-tour="tour-assistant-close"
        >
          &#x2715;
        </button>
      </form>

      <p
        *ngIf="
          assistant.query().trim().length >= 2 && assistant.results().length === 0
        "
        class="tour-assistant-empty"
        data-tour="tour-assistant-empty"
      >
        No matching steps. Try different words.
      </p>

      <ul
        *ngIf="assistant.results().length > 0"
        class="tour-assistant-results"
        role="listbox"
        data-tour="tour-assistant-results"
      >
        <li
          *ngFor="let match of assistant.results(); trackBy: trackByMatch"
        >
          <button
            type="button"
            class="tour-assistant-result"
            (click)="assistant.jumpTo(match)"
            [rpTooltip]="resultTooltip(match)"
            data-tour="tour-assistant-result"
          >
            <span class="tour-assistant-result-title">{{ match.title }}</span>
            <span
              *ngIf="match.snippet"
              class="tour-assistant-result-snippet"
            >
              {{ stripTourMarkup(match.snippet) }}
            </span>
            <span class="tour-assistant-result-meta">
              <span class="tour-assistant-result-tour">
                {{
                  match.tourId === assistant.currentTourId()
                    ? 'This tour'
                    : match.tourId
                }}{{
                  match.kind === 'chapter' && match.stepCount
                    ? ' • ' + match.stepCount + ' steps'
                    : ''
                }}
              </span>
              <span class="tour-assistant-result-jump">
                {{ match.kind === 'chapter' ? 'Open flow →' : 'Jump →' }}
              </span>
            </span>
          </button>
        </li>
      </ul>
    </div>
  `,
})
export class TourAssistantPromptComponent {
  @Input() placeholder = 'Ask the tour…';

  @ViewChild('inputEl') inputEl?: ElementRef<HTMLInputElement>;

  constructor(readonly assistant: TourAssistantService) {
    effect(() => {
      if (this.assistant.open()) {
        queueMicrotask(() => this.inputEl?.nativeElement.focus());
      }
    });
  }

  handleSubmit(event: Event): void {
    event.preventDefault();
    this.assistant.submit();
  }

  trackByMatch = (_index: number, match: AssistantMatch): string =>
    `${match.kind ?? 'step'}:${match.tourId}:${match.stepId}:${match.chapter ?? ''}`;

  stripTourMarkup(snippet: string): string {
    return snippet.replace(/==\|?~?([^=|~]+)~?\|?==/g, '$1');
  }

  resultTooltip(match: AssistantMatch): string {
    const cleanSnippet = match.snippet ? this.stripTourMarkup(match.snippet).trim() : '';
    return cleanSnippet ? `${match.title}\n\n${cleanSnippet}` : match.title;
  }
}
